doctrine:
    dbal:
        default_connection: website
        connections:
            website:
                # configure these for your database server
                url: '%env(DATABASE_WEBSITE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            forum:
                # configure these for your database server
                url: '%env(DATABASE_FORUM_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                mapping_types:
                    enum: string
            berrygames:
                # configure these for your database server
                url: '%env(DATABASE_BERRYGAMES_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                mapping_types:
                    enum: string
                    bit: boolean

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: website
        entity_managers:
            website:
                connection: website
                mappings:
                    Website:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Website'
                        prefix: 'App\Entity\Website'
                        alias: Website
            forum:
                connection: forum
                mappings:
                    Forum:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Forum'
                        prefix: 'App\Entity\Forum'
                        alias: Forum
            berrygames:
                connection: berrygames
                mappings:
                    Berrygames:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Berrygames'
                        prefix: 'App\Entity\Berrygames'
                        alias: Berrygames
